fish_data = [
    {"name": "명태", "ban_period": "1.1~12.31"},
    {"name": "대구", "ban_period": "1.16~2.15", "min_size_cm": 35},
    {"name": "가리비", "ban_period": "3.1~6.30"},
    {"name": "살오징어", "ban_period": "4.1~5.31", "exception": "근해채낚기, 연안복합, 정치망은 4.1~4.30", "min_size_cm": 15},
    {"name": "고등어", "ban_period": "4.1~6.30 중 1개월", "min_size_cm": 21},
    {"name": "코끼리조개", "ban_period": "5.1~6.30", "region": "강원,경북"},
    {"name": "감성돔", "ban_period": "5.1~5.31", "min_size_cm": 25},
    {"name": "삼치", "ban_period": "5.1~5.31"},
    {"name": "참문어", "ban_period": "5.16~6.30", "optional_period": "5.1~9.15 중 46일 이상"},
    {"name": "대하", "ban_period": "5.1~5.31"},
    {"name": "전어", "ban_period": "5.1~7.15", "exception": "강원,경북 제외"},
    {"name": "말쥐치", "ban_period": "5.1~7.31", "min_size_cm": 18},
    {"name": "주꾸미", "ban_period": "5.11~8.31"},
    {"name": "낙지", "ban_period": "6.1~6.30", "optional_period": "4.1~9.30 중 1개월 이상"},
    {"name": "참홍어", "ban_period": "6.1~7.15", "min_size_cm": 42},
    {"name": "꽃게", "ban_period": "6.21~8.20", "exception": ["연평 7.1~8.31", "백령, 대청, 소청 7.16~9.15"], "min_size_cm": 6.4},
    {"name": "소라", "ban_periods": [
        {"region": "여수 삼산면", "period": "6.1~6.30"},
        {"region": "제주", "period": "6.1~8.31"},
        {"region": "제주 추자도", "period": "7.1~8.31"},
        {"region": "울릉,독도", "period": "6.1~7.31"}
    ], "min_size_cm": {"제주": 5, "울릉, 독도": 7}},
    {"name": "새조개", "ban_period": "6.16~9.30", "exception": "부산, 울산, 경남, 전남, 제주 6.1~9.30"},
    {"name": "대게", "ban_period": "6.1~11.30", "min_size_cm": 9},
    {"name": "갈치", "ban_period": "7.1~7.31", "exception": "근해채낚기, 연안복합 제외", "min_size_cm": 18},
    {"name": "참조기", "ban_period": "7.1~7.31", "exception": "유자망 4.22~8.10", "min_size_cm": 15},
    {"name": "해삼", "ban_period": "7.1~7.31"},
    {"name": "오분자기", "ban_period": "7.1~8.31", "region": "제주", "min_size_cm": 4},
    {"name": "키조개", "ban_period": "7.1~8.31", "region": "부산, 울산, 강원, 경북, 경남", "min_size_cm": 18},
    {"name": "붉은대게", "ban_period": "7.10~8.25", "exception": "강원 연안자망 6.1~7.10"},
    {"name": "옥돔", "ban_period": "7.21~8.20"},
    {"name": "전복류", "ban_period": "9.1~10.31", "exception": "제주 10.1~12.31", "min_size_cm": {"제주": 10, "기타": 7}},
    {"name": "넓미역", "ban_period": "9.1~11.30", "optional_period": "5.1~11.30 중 3개월 이상", "region": "제주"},
    {"name": "연어", "ban_period": "10.1~11.30"},
    {"name": "톳", "ban_period": "10.1~익년 1.31"},
    {"name": "쥐노래미", "ban_period": "11.1~12.31", "min_size_cm": 20},
    {"name": "우뭇가사리", "ban_period": "11.1~익년 3.31"},
    {"name": "문치가자미", "ban_period": "12.1~익년 1.31", "min_size_cm": 20},
    {"name": "기름가자미", "min_size_cm": 20},
    {"name": "기수재첩", "min_size_cm": 1.5},
    {"name": "갯장어", "min_size_cm": 40},
    {"name": "넙치", "min_size_cm": 35},
    {"name": "농어", "min_size_cm": 30},
    {"name": "도루묵", "min_size_cm": 11},
    {"name": "대문어", "min_weight_g": 600},
    {"name": "돌돔", "min_size_cm": 24},
    {"name": "미거지", "min_size_cm": 40},
    {"name": "민어", "min_size_cm": 33},
    {"name": "방어", "min_size_cm": 30},
    {"name": "볼락", "min_size_cm": 15},
    {"name": "붕장어", "min_size_cm": 35},
    {"name": "용가자미", "min_size_cm": 20},
    {"name": "조피볼락", "min_size_cm": 23},
    {"name": "참가자미", "min_size_cm": 20},
    {"name": "참돔", "min_size_cm": 24},
    {"name": "청어", "min_size_cm": 20},
    {"name": "꽃게 암컷", "ban_period": "연중 포획금지", "condition": "복부 외포란 상태"},
    {"name": "대게 암컷", "ban_period": "연중 포획금지"},
    {"name": "붉은대게 암컷", "ban_period": "연중 포획금지"}
]
